---
jobs:
- name: update-stemcells-rn
  public: false
  serial: true
  plan:
    - get: every-15m
      trigger: true
    - get: docs-stemcell-rn
    - task: update-stemcells-rn
      file: docs-stemcell-rn/ci/task.yml
      params:
        GITHUB_ACCESS_TOKEN: {{github_access_token}}
      ensure:
        put: docs-stemcell-rn
        params:
          repository: updated-docs-stemcell-rn
          rebase: true

resources:
- name: docs-stemcell-rn
  type: git
  source:
    uri: git@github.com:pivotal-cf/docs-stemcell-rn
    branch: master
    private_key: {{github_private_key}}

- name: every-15m
  type: time
  source: {interval: 15m}

